// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Wdpr_Groep_E.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220105153523_SqliteDatbaseErbij")]
    partial class SqliteDatbaseErbij
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");
#pragma warning restore 612, 618
        }
    }
}
